Traceback (most recent call last):
  File "/home/qcqced/바탕화면/ML_Test/UPPPM/train.py", line 53, in <module>
    main('upppm_config.json', CFG)
  File "/home/qcqced/바탕화면/ML_Test/UPPPM/train.py", line 34, in main
    getattr(train_loop, cfg.loop)(cfg)  # init object
  File "/home/qcqced/바탕화면/ML_Test/UPPPM/trainer/train_loop.py", line 35, in train_loop
    loader_train, loader_valid, train, valid_labels = train_input.make_batch(fold)
  File "/home/qcqced/바탕화면/ML_Test/UPPPM/trainer/trainer.py", line 58, in make_batch
    collate_fn=collate(valid_dataset[0].input_ids),
AttributeError: 'tuple' object has no attribute 'input_ids'